### ISSUE TITLE
`polygon` function not used in RandomArcs.pde

### ISSUE THREAD

**Issue by cjmlgrto** [bjango/Processing-SVG-experiments#1]
The `polygon` function in the file `RandomArcs.pde` is defined but not used. Consider removing it from the script? 😄

**Comment by marcedwards** [comment]
Oops! Thanks for spotting that. Fixed in https://github.com/bjango/Processing-SVG-experiments/commit/6654e96c8a482ac0f4f1137d6f2b3cd5db8e1d6e .
